/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SistemBengkelPackage;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows10
 */
public class Form_BuatAkun extends javax.swing.JFrame {

    Connection conn;
    Statement stat;
    ResultSet rs;
    String query, nameDB="SBD", nameTabel = "Staf";

    public Form_BuatAkun() throws ClassNotFoundException {
        initComponents();
        Koneksi_DataBase DB = new Koneksi_DataBase();
        DB.Bengkel_Connection();
        conn = DB.conn;
        stat = DB.stat;
        tampil_akun();
        try {
            CariData("St");
        } catch (SQLException ex) {
            Logger.getLogger(Form_BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);
    }

    public ArrayList<Akun> akunList() {
        ArrayList<Akun> akunList = new ArrayList<>();
        try {
            query = "SELECT * FROM " + nameTabel;
            stat = conn.createStatement();
            rs = stat.executeQuery(query);
            Akun akun;
            while (rs.next()) {
                if (rs.getString("Deleted").replaceAll("\\s+", "").equals("0")) {
                    akun = new Akun(rs.getString("IDStaff").replaceAll("\\s+", ""), rs.getString("NamaStaff").replaceAll("\\s+", ""));
                    akunList.add(akun);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        return akunList;
    }

    public void tampil_akun() {
        ArrayList<Akun> list = akunList();
        DefaultTableModel model = (DefaultTableModel) tb_akun.getModel();
        Object[] row = new Object[2];
        for (int i = 0; i < list.size(); i++) {
            row[0] = list.get(i).getIDStaff();
            row[1] = list.get(i).getNamaStaff();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btn_ptg = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txt_idstaff = new javax.swing.JTextField();
        txt_namastaff = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_edit = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_akun = new javax.swing.JTable();
        txt_pass = new javax.swing.JPasswordField();
        txt_konfir_pass = new javax.swing.JPasswordField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txt_caridata = new javax.swing.JTextField();
        txt_posisi = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_area_alamat = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gambar/logo.png"))); // NOI18N

        btn_ptg.setBackground(new java.awt.Color(0, 0, 51));
        btn_ptg.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_ptg.setForeground(new java.awt.Color(255, 255, 255));
        btn_ptg.setText("BACK TO LOGIN");
        btn_ptg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ptgActionPerformed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(0, 0, 51));
        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("IDStaff");

        jLabel4.setBackground(new java.awt.Color(0, 0, 51));
        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nama");

        jLabel5.setBackground(new java.awt.Color(0, 0, 51));
        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pasword");

        txt_idstaff.setBackground(new java.awt.Color(0, 0, 51));
        txt_idstaff.setForeground(new java.awt.Color(255, 255, 255));

        txt_namastaff.setBackground(new java.awt.Color(0, 0, 51));
        txt_namastaff.setForeground(new java.awt.Color(255, 255, 255));
        txt_namastaff.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt_namastaffKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(0, 0, 51));
        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Konfirmasi Password");

        btn_save.setBackground(new java.awt.Color(0, 0, 51));
        btn_save.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_save.setForeground(new java.awt.Color(255, 255, 255));
        btn_save.setText("TAMBAH");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });

        btn_edit.setBackground(new java.awt.Color(0, 0, 51));
        btn_edit.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_edit.setForeground(new java.awt.Color(255, 255, 255));
        btn_edit.setText("EDIT");
        btn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editActionPerformed(evt);
            }
        });

        btn_delete.setBackground(new java.awt.Color(0, 0, 51));
        btn_delete.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        btn_delete.setForeground(new java.awt.Color(255, 255, 255));
        btn_delete.setText("HAPUS");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });

        tb_akun.setBackground(new java.awt.Color(0, 0, 51));
        tb_akun.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        tb_akun.setForeground(new java.awt.Color(255, 255, 255));
        tb_akun.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "IDStaff", "Nama"
            }
        ));
        tb_akun.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_akunMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tb_akun);

        txt_pass.setBackground(new java.awt.Color(0, 0, 51));
        txt_pass.setForeground(new java.awt.Color(255, 255, 255));

        txt_konfir_pass.setBackground(new java.awt.Color(0, 0, 51));
        txt_konfir_pass.setForeground(new java.awt.Color(255, 255, 255));

        jLabel7.setBackground(new java.awt.Color(0, 0, 51));
        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Alamat");

        jLabel8.setBackground(new java.awt.Color(0, 0, 51));
        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Posisi");

        txt_caridata.setBackground(new java.awt.Color(0, 0, 51));
        txt_caridata.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        txt_caridata.setForeground(new java.awt.Color(255, 255, 255));
        txt_caridata.setText("Cari Data (Ketik IDStaff)");
        txt_caridata.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_caridataKeyTyped(evt);
            }
        });

        txt_posisi.setBackground(new java.awt.Color(0, 0, 51));
        txt_posisi.setForeground(new java.awt.Color(255, 255, 255));

        txt_area_alamat.setBackground(new java.awt.Color(0, 0, 51));
        txt_area_alamat.setColumns(20);
        txt_area_alamat.setForeground(new java.awt.Color(255, 255, 255));
        txt_area_alamat.setRows(5);
        jScrollPane3.setViewportView(txt_area_alamat);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_idstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_namastaff, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_posisi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 1, Short.MAX_VALUE)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(20, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(txt_konfir_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_ptg, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txt_caridata)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ptg, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_idstaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txt_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txt_konfir_pass, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_namastaff, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_posisi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txt_caridata, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_save, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btn_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(51, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_akunMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_akunMouseClicked
        tb_akun.setSelectionForeground(Color.GREEN);
        try {
            int baris = tb_akun.rowAtPoint(evt.getPoint());
            String idstaff = tb_akun.getValueAt(baris, 0).toString();
            query = "SELECT * FROM " + nameTabel + " WHERE IDStaff='" + idstaff.replaceAll("\\s+", "") + "'";
            stat = conn.createStatement();
            rs = stat.executeQuery(query);

            String namastaff = "", alamat = "", posisi = "", pw = "";

            if (rs.next()) {
                namastaff = String.valueOf(rs.getString("NamaStaff")).replaceAll("null", "").replaceAll("\\s+", "");
                alamat = String.valueOf(rs.getString("Alamat")).replaceAll("null", "").replaceAll("\\s+", "");
                posisi = String.valueOf(rs.getString("Posisi")).replaceAll("null", "").replaceAll("\\s+", "");
                pw = String.valueOf(rs.getString("Password")).replaceAll("null", "").replaceAll("\\s+", "");
            }

            txt_idstaff.setText(idstaff);
            txt_namastaff.setText(namastaff);
            txt_area_alamat.setText(alamat);
            txt_caridata.setText(posisi);
            txt_pass.setText(pw);
            txt_konfir_pass.setText(pw);

        } catch (SQLException ex) {
            Logger.getLogger(Form_BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_tb_akunMouseClicked

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        try {
            int row = tb_akun.getSelectedRow();
            String value = (tb_akun.getModel().getValueAt(row, 0).toString());
//            query = "DELETE FROM Login WHERE IDStaff = '" + txt_idstaff.getText() + "'";
            query = "UPDATE " + nameTabel + " SET Deleted='1' WHERE IDStaff='" + value.replaceAll("\\s+", "") + "'";
            PreparedStatement pst = conn.prepareStatement(query);
            pst.executeUpdate();
            DefaultTableModel model = (DefaultTableModel) tb_akun.getModel();
            model.setRowCount(0);
            tampil_akun();
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editActionPerformed
        try {
            int row = tb_akun.getSelectedRow();
            String value = (tb_akun.getModel().getValueAt(row, 0).toString());
            click_edit(value);
            DefaultTableModel model = (DefaultTableModel) tb_akun.getModel();
            model.setRowCount(0);
            tampil_akun();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diupdate");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btn_editActionPerformed

    private void click_edit(String idstaff) throws SQLException, Exception {
        if (!(txt_pass.getText().equals(txt_konfir_pass.getText()))) {
            throw new Exception("Password Harus Sama");
        }

        query = "UPDATE " + nameTabel + " SET IDStaff=?, NamaStaff=?, Alamat=?, Posisi=?, Keterangan=?, Deleted=?,Password=? WHERE IDStaff = '" + idstaff.replaceAll("\\s+", "") + "'";
        PreparedStatement pst = conn.prepareStatement(query);
        pst.setString(1, idstaff);
        pst.setString(2, txt_namastaff.getText());
        pst.setString(3, txt_area_alamat.getText());
        pst.setString(4, txt_posisi.getText());
        pst.setString(5, "-");
        pst.setString(6, "0");
        pst.setString(7, txt_pass.getText());
        pst.executeUpdate();
        txt_idstaff.setText("");
        txt_namastaff.setText("");
        txt_area_alamat.setText("");
        txt_caridata.setText("");
        txt_pass.setText("");
    }

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        try {
            if (!(txt_pass.getText().equals(txt_konfir_pass.getText()))) {
                throw new Exception("Password Harus Sama");
            }

            query = "SELECT * FROM " + nameTabel + " WHERE IDStaff='" + txt_idstaff.getText().replaceAll("\\s+", "") + "'";
            
            stat = conn.createStatement();
            rs = stat.executeQuery(query);
            if (rs.next()) {
                if (rs.getString("Deleted").replaceAll("\\s+", "").equals("1")) {
                    click_edit(txt_idstaff.getText());
                    tampil_akun();
                } else {
                    throw new Exception("Akun Sudah Ada\nKlik data lalu tekan edit jika ingin merubah data");
                }
            } else {
                if (!txt_idstaff.getText().replaceAll("\\s+", "").equals("")) {
                    query = "INSERT INTO " + nameTabel + " (IDStaff,NamaStaff,Alamat,Posisi,Keterangan,Deleted,Password) VALUES (?,?,?,?,?,?,?)";
                    PreparedStatement pst = conn.prepareStatement(query);
                    pst.setString(1, txt_idstaff.getText());
                    pst.setString(2, txt_namastaff.getText());
                    pst.setString(3, txt_area_alamat.getText());
                    pst.setString(4, txt_caridata.getText());
                    pst.setString(5, "-");
                    pst.setString(6, "0");
                    pst.setString(7, txt_pass.getText());
                    pst.executeUpdate();
                } else {
                    throw new Exception("Data Tidak Boleh Kosong");
                }
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Disimpan");
            DefaultTableModel model = (DefaultTableModel) tb_akun.getModel();
            model.setRowCount(0);
            tampil_akun();
            txt_idstaff.setText("");
            txt_namastaff.setText("");
            txt_area_alamat.setText("");
            txt_caridata.setText("");
            txt_pass.setText("");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Penyimpanan Data Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_ptgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ptgActionPerformed
        this.setVisible(false);
        try {
            new Login().setVisible(true);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Form_BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_ptgActionPerformed

    private void txt_caridataKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_caridataKeyTyped
        // TODO add your handling code here:
        try {
            CariData(txt_caridata.getText());
        } catch (SQLException ex) {
            Logger.getLogger(Form_BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txt_caridataKeyTyped

    private void txt_namastaffKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_namastaffKeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txt_namastaffKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form_BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form_BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form_BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form_BuatAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Form_BuatAkun().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(Form_BuatAkun.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_edit;
    private javax.swing.JButton btn_ptg;
    private javax.swing.JButton btn_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tb_akun;
    private javax.swing.JTextArea txt_area_alamat;
    private javax.swing.JTextField txt_caridata;
    private javax.swing.JTextField txt_idstaff;
    private javax.swing.JPasswordField txt_konfir_pass;
    private javax.swing.JTextField txt_namastaff;
    private javax.swing.JPasswordField txt_pass;
    private javax.swing.JTextField txt_posisi;
    // End of variables declaration//GEN-END:variables

    private static class Akun {

        private String IDStaff, NamaStaff;

        public Akun(String IDStaff, String NamaStaff) {
            this.IDStaff = IDStaff;
            this.NamaStaff = NamaStaff;
        }

        public String getIDStaff() {
            return IDStaff;
        }

        public String getNamaStaff() {
            return NamaStaff;
        }

    }

    private void CariData(String cd) throws SQLException {
        query = "SELECT * FROM " + nameTabel + " WHERE IDStaff like '" + cd + "%'";
        stat = conn.createStatement();
        rs = stat.executeQuery(query);
        if (rs.next()) {
            ArrayList<Akun> akunList = new ArrayList<>();
            try {
                Akun akun;
                if (rs.getString("Deleted").replaceAll("\\s+", "").equals("0")) {
                    akun = new Akun(rs.getString("IDStaff").replaceAll("\\s+", ""), rs.getString("NamaStaff").replaceAll("\\s+", ""));
                    akunList.add(akun);
                }
                while (rs.next()) {
                    if (rs.getString("Deleted").replaceAll("\\s+", "").equals("0")) {
                        akun = new Akun(rs.getString("IDStaff").replaceAll("\\s+", ""), rs.getString("NamaStaff").replaceAll("\\s+", ""));
                        akunList.add(akun);
                    }
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

            DefaultTableModel model = (DefaultTableModel) tb_akun.getModel();
            model.setRowCount(0);
            Object[] row = new Object[2];
            for (Iterator<Akun> it = akunList.iterator(); it.hasNext();) {
                Akun akunList1 = it.next();
                row[0] = akunList1.getIDStaff();
                row[1] = akunList1.getNamaStaff();
                model.addRow(row);
            }
        }
    }
}
